name: Docker

on:
  pull_request:
    types:
      - closed
    branches:
      - dev
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build_and_push_to_registry:
    name: Build and push Docker image to Docker Hub
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Build Docker Image
        run: docker build . --file Dockerfile --tag $DOCKERHUB_USERNAME/${{ secrets.REPOSITORY_NAME }}:${{ steps.date.outputs.date }}

      - name: Push Docker Image to Docker Hub
        run: docker push $DOCKERHUB_USERNAME/${{ secrets.REPOSITORY_NAME }}:${{ steps.date.outputs.date }}
