name: Docker

on:
  push:
    branches:
      - main
      - dev

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REPOSITORY_NAME: ${{ secrets.REPOSITORY_NAME }}

jobs:
  build_and_push_to_registry:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"

      - name: Check if Docker image exists on Docker Hub
        id: check_image
        run: |
          IMAGE_NAME=$DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{ steps.date.outputs.date }}
          docker pull $IMAGE_NAME > /dev/null 2>&1 || echo "::set-output name=image_exists::false"
          
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=$DOCKERHUB_USERNAME/$REPOSITORY_NAME:${{ steps.date.outputs.date }}
          if [[ "${{ steps.check_image.outputs.image_exists }}" == "false" ]]; then
            docker build -t $IMAGE_NAME .
          fi
          docker push $IMAGE_NAME
